version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - cd frontend
      - npm install

  build:
    commands:
      - cd frontend
      - chmod -R +x node_modules/.bin   # Fix permissions to avoid exit code 126
      - npm run build

artifacts:
  files:
    - '**/*'
  base-directory: frontend/dist
