version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - cd frontend
      - npm install
      - cd ../backend
      - npm install
  build:
    commands:
      - echo Building frontend...
      - cd ../frontend
      - npm run build
      - echo Preparing backend...
      - cd ../backend
      - echo Skipping backend build (if static).
artifacts:
  files:
    - '**/*'
  base-directory: frontend/dist
