version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing backend dependencies...
      - cd backend && npm install
      - cd ../frontend
      - echo Installing frontend dependencies...
      - npm install
      - cd ..

  pre_build:
    commands:
      - echo Running pre-build checks...
      - echo Current date: `date`
      - echo Checking backend dependencies...
      - cd backend && npm list --depth=0
      - cd ../frontend
      - echo Checking frontend dependencies...
      - npm list --depth=0
      - cd ..

  build:
    commands:
      - echo Building React frontend...
      - cd frontend && npm run build
      - cd ..
      - echo Creating dist directory...
      - mkdir -p dist
      - cp -r frontend/build/* dist/
      - echo Build completed on `date`

  post_build:
    commands:
      - echo Post-build steps...
      - echo Listing contents of dist directory:
      - ls -la dist/
      - echo Build process finished successfully

artifacts:
  files:
    - '**/*'
  base-directory: dist

cache:
  paths:
    - 'backend/node_modules/**/*'
    - 'frontend/node_modules/**/*'
