version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - cd frontend
      - npm install

  build:
    commands:
      - npm run build  # Do NOT cd again — already inside frontend!

artifacts:
  files:
    - frontend/dist/**/*  # Output files to deploy
  base-directory: frontend/dist
